### ISSUE TITLE
Searching path and file name

### ISSUE THREAD

**Issue by mixa-pulemet** [SamLangTen/MusicbeeLocalLyricsLoader#1]
I'm a noob in programming. My knowledge was only enough to compile the dll and put it in the Plugins folder. The plugin is working, but it downloads the lyrics only from the folder with the music file and with a full name match. Adding your own directory and your own download pattern does not work. Is it possible to fix it or am I doing something wrong?

**Comment by SamLangTen** [comment]
could you provide your settings in plugins settings?

**Comment by mixa-pulemet** [comment]
![Снимок экрана 2024-06-01 234709](https://github.com/SamLangTen/MusicBeeLocalLyricsLoader/assets/110778140/c6b58da5-a119-432b-bcc7-55aca36814f8)
![Снимок экрана 2024-06-01 234747](https://github.com/SamLangTen/MusicBeeLocalLyricsLoader/assets/110778140/3e64e05c-31e3-41bf-b7a4-f2532af61c7b)

**Comment by mixa-pulemet** [comment]
> не могли бы вы указать свои настройки в настройках плагинов?

![Снимок экрана 2024-06-01 234709](https://github.com/SamLangTen/MusicBeeLocalLyricsLoader/assets/110778140/5e8ccfc3-7052-41d2-b01d-c06f7a9e73e3)
![Снимок экрана 2024-06-01 234747](https://github.com/SamLangTen/MusicBeeLocalLyricsLoader/assets/110778140/9d220ae0-38e7-42c1-8dc5-ee0d28dae64e)

**Comment by mixa-pulemet** [comment]
> could you provide your settings in plugins settings?

![Снимок экрана 2024-06-01 234709](https://github.com/SamLangTen/MusicBeeLocalLyricsLoader/assets/110778140/128d7fb6-1ac0-4af7-ae6f-419585470a44)
![Снимок экрана 2024-06-01 234747](https://github.com/SamLangTen/MusicBeeLocalLyricsLoader/assets/110778140/37a1ec3c-8522-4696-8eca-c3cda56b8f68)

**Comment by SamLangTen** [comment]
> > could you provide your settings in plugins settings?
> 
> ![Снимок экрана 2024-06-01 234709](https://private-user-images.githubusercontent.com/110778140/335826846-128d7fb6-1ac0-4af7-ae6f-419585470a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODE2MzgsIm5iZiI6MTcxNzM4MTMzOCwicGF0aCI6Ii8xMTA3NzgxNDAvMzM1ODI2ODQ2LTEyOGQ3ZmI2LTFhYzAtNGFmNy1hZTZmLTQxOTU4NTQ3MGE0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMjIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGY3Yzk1MTAyODM4MGU5YmJhMmQ1NTVhMzEyODY3MzM4ZjFmNGYxNWNkMDNkNDFhOWQwMDliOGZhYzdiNTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pb6oMNNEZgxm8A3cQtVSB_6MJ-YELDNzR757s0pyklA) ![Снимок экрана 2024-06-01 234747](https://private-user-images.githubusercontent.com/110778140/335826848-37a1ec3c-8522-4696-8eca-c3cda56b8f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODE2MzgsIm5iZiI6MTcxNzM4MTMzOCwicGF0aCI6Ii8xMTA3NzgxNDAvMzM1ODI2ODQ4LTM3YTFlYzNjLTg1MjItNDY5Ni04ZWNhLWMzY2RhNTZiOGY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwMjIyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmIzOTI4M2RjMTc5YTQ3N2FkOTU4Njk1NTFiODRlZGNlNTdiYjdiOTE5ZGVjZjQ2NDJhZTZiZDI0ZGU0NDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M5GiHMQKd94pYtgsZFSb39Ca52q2t4JfAINZyQ7kAiI)

Each pattern or path should be separated by a newline instead of a comma.
In file pattern, your settings could be:
```
{title}.lrc
{artist} - {title}.lrc
{filename}.lrc
```
